import universe from "./Pages/Blogs/images/universespider.jpeg"
import newyork from "./Pages/Blogs/images/newyorkspider.jpeg"
import german from "./Pages/Blogs/images/germanspider.jpeg"
import space from "./Pages/Blogs/images/spacespider.jpeg"

let content = [
    {
        title: "Universal Chaos",
        image: universe,
        author: "Alex",
        date: "09/09/8099",
        p1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut congue feugiat pulvinar. Sed vel ex a elit consectetur vestibulum aliquam rhoncus purus. Maecenas ullamcorper non ligula sit amet rhoncus. Integer non ultrices sapien. Cras elit justo, varius a consectetur non, vehicula vitae est. Maecenas in nisi quis arcu molestie mollis. Etiam et luctus ante, id ornare nisl. Morbi eu justo lectus. Vestibulum sodales leo in nisl aliquam, sit amet sagittis nunc efficitur. Vivamus nec lectus dui.",
        p2: "Nam sit amet augue eget risus efficitur vulputate et id ante. Etiam nisi magna, tempor sed magna posuere, ornare gravida nibh. Fusce sit amet viverra sapien. Nam sit amet metus a nibh faucibus gravida ut in metus. Vivamus venenatis neque at metus rutrum, et fringilla ante faucibus. Sed leo arcu, dictum a leo vitae, dignissim gravida mi. Donec scelerisque posuere justo. Sed maximus tempus tellus vitae feugiat.",
        p3: "Cras libero dui, tincidunt ac auctor at, convallis quis ante. Curabitur mi sem, feugiat et velit sed, fermentum malesuada erat. Fusce eu lectus mi. Aenean suscipit ornare risus, ac pellentesque risus mollis in. Maecenas in libero vitae sem pulvinar tincidunt. Curabitur id enim non purus aliquam lobortis. Nullam lacinia purus ac eros gravida malesuada.",
        p4: "Nulla nisl enim, lacinia ac magna quis, dictum mattis diam. Nulla in mi diam. Mauris id mauris in est pharetra efficitur. Nam lacus ex, feugiat vitae nunc bibendum, ullamcorper mattis libero. Donec tincidunt justo ut risus bibendum, ornare mattis orci ultricies. Phasellus vestibulum velit sodales lorem fringilla congue. Duis sagittis sagittis dui nec tincidunt. Nullam tempor pellentesque orci ultrices lobortis. Phasellus ut orci a felis tempor tempus consectetur nec nisi. Etiam sed mattis ante. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec id ipsum sollicitudin, luctus nisl quis, tristique arcu. Nam eget enim imperdiet, scelerisque felis ut, interdum ante.",
        p5: "Donec sollicitudin diam et volutpat ultricies. Sed porta volutpat risus, nec condimentum ligula euismod a. Praesent feugiat felis a porta malesuada. Morbi justo tellus, mollis at ipsum ut, condimentum hendrerit metus. Donec eu lacus tempor, malesuada lacus quis, euismod sem. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer gravida euismod fringilla. Praesent blandit vehicula laoreet. Proin vestibulum sit amet sapien et sodales. Nunc quis tortor et nunc mollis malesuada vel sed eros. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut bibendum varius odio, auctor semper quam. Aliquam sed aliquet nisi. In neque massa, faucibus vel ante id, ultrices varius lacus. Phasellus tincidunt vitae nulla ut auctor.",
    },
    {
        title: "Space Adventure",
        image: space,
        author: "Ned",
        date: "03/24/2019",
        p1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut congue feugiat pulvinar. Sed vel ex a elit consectetur vestibulum aliquam rhoncus purus. Maecenas ullamcorper non ligula sit amet rhoncus. Integer non ultrices sapien. Cras elit justo, varius a consectetur non, vehicula vitae est. Maecenas in nisi quis arcu molestie mollis. Etiam et luctus ante, id ornare nisl. Morbi eu justo lectus. Vestibulum sodales leo in nisl aliquam, sit amet sagittis nunc efficitur. Vivamus nec lectus dui.",
        p2: "Nam sit amet augue eget risus efficitur vulputate et id ante. Etiam nisi magna, tempor sed magna posuere, ornare gravida nibh. Fusce sit amet viverra sapien. Nam sit amet metus a nibh faucibus gravida ut in metus. Vivamus venenatis neque at metus rutrum, et fringilla ante faucibus. Sed leo arcu, dictum a leo vitae, dignissim gravida mi. Donec scelerisque posuere justo. Sed maximus tempus tellus vitae feugiat.",
        p3: "Cras libero dui, tincidunt ac auctor at, convallis quis ante. Curabitur mi sem, feugiat et velit sed, fermentum malesuada erat. Fusce eu lectus mi. Aenean suscipit ornare risus, ac pellentesque risus mollis in. Maecenas in libero vitae sem pulvinar tincidunt. Curabitur id enim non purus aliquam lobortis. Nullam lacinia purus ac eros gravida malesuada.",
        p4: "Nulla nisl enim, lacinia ac magna quis, dictum mattis diam. Nulla in mi diam. Mauris id mauris in est pharetra efficitur. Nam lacus ex, feugiat vitae nunc bibendum, ullamcorper mattis libero. Donec tincidunt justo ut risus bibendum, ornare mattis orci ultricies. Phasellus vestibulum velit sodales lorem fringilla congue. Duis sagittis sagittis dui nec tincidunt. Nullam tempor pellentesque orci ultrices lobortis. Phasellus ut orci a felis tempor tempus consectetur nec nisi. Etiam sed mattis ante. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec id ipsum sollicitudin, luctus nisl quis, tristique arcu. Nam eget enim imperdiet, scelerisque felis ut, interdum ante.",
        p5: "Donec sollicitudin diam et volutpat ultricies. Sed porta volutpat risus, nec condimentum ligula euismod a. Praesent feugiat felis a porta malesuada. Morbi justo tellus, mollis at ipsum ut, condimentum hendrerit metus. Donec eu lacus tempor, malesuada lacus quis, euismod sem. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer gravida euismod fringilla. Praesent blandit vehicula laoreet. Proin vestibulum sit amet sapien et sodales. Nunc quis tortor et nunc mollis malesuada vel sed eros. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut bibendum varius odio, auctor semper quam. Aliquam sed aliquet nisi. In neque massa, faucibus vel ante id, ultrices varius lacus. Phasellus tincidunt vitae nulla ut auctor.",
    },
    {
        title: "The Hero From Queens",
        image: newyork,
        author: "Peter Parker",
        date: "08/04/2018",
        p1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut congue feugiat pulvinar. Sed vel ex a elit consectetur vestibulum aliquam rhoncus purus. Maecenas ullamcorper non ligula sit amet rhoncus. Integer non ultrices sapien. Cras elit justo, varius a consectetur non, vehicula vitae est. Maecenas in nisi quis arcu molestie mollis. Etiam et luctus ante, id ornare nisl. Morbi eu justo lectus. Vestibulum sodales leo in nisl aliquam, sit amet sagittis nunc efficitur. Vivamus nec lectus dui.",
        p2: "Nam sit amet augue eget risus efficitur vulputate et id ante. Etiam nisi magna, tempor sed magna posuere, ornare gravida nibh. Fusce sit amet viverra sapien. Nam sit amet metus a nibh faucibus gravida ut in metus. Vivamus venenatis neque at metus rutrum, et fringilla ante faucibus. Sed leo arcu, dictum a leo vitae, dignissim gravida mi. Donec scelerisque posuere justo. Sed maximus tempus tellus vitae feugiat.",
        p3: "Cras libero dui, tincidunt ac auctor at, convallis quis ante. Curabitur mi sem, feugiat et velit sed, fermentum malesuada erat. Fusce eu lectus mi. Aenean suscipit ornare risus, ac pellentesque risus mollis in. Maecenas in libero vitae sem pulvinar tincidunt. Curabitur id enim non purus aliquam lobortis. Nullam lacinia purus ac eros gravida malesuada.",
        p4: "Nulla nisl enim, lacinia ac magna quis, dictum mattis diam. Nulla in mi diam. Mauris id mauris in est pharetra efficitur. Nam lacus ex, feugiat vitae nunc bibendum, ullamcorper mattis libero. Donec tincidunt justo ut risus bibendum, ornare mattis orci ultricies. Phasellus vestibulum velit sodales lorem fringilla congue. Duis sagittis sagittis dui nec tincidunt. Nullam tempor pellentesque orci ultrices lobortis. Phasellus ut orci a felis tempor tempus consectetur nec nisi. Etiam sed mattis ante. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec id ipsum sollicitudin, luctus nisl quis, tristique arcu. Nam eget enim imperdiet, scelerisque felis ut, interdum ante.",
        p5: "Donec sollicitudin diam et volutpat ultricies. Sed porta volutpat risus, nec condimentum ligula euismod a. Praesent feugiat felis a porta malesuada. Morbi justo tellus, mollis at ipsum ut, condimentum hendrerit metus. Donec eu lacus tempor, malesuada lacus quis, euismod sem. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer gravida euismod fringilla. Praesent blandit vehicula laoreet. Proin vestibulum sit amet sapien et sodales. Nunc quis tortor et nunc mollis malesuada vel sed eros. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut bibendum varius odio, auctor semper quam. Aliquam sed aliquet nisi. In neque massa, faucibus vel ante id, ultrices varius lacus. Phasellus tincidunt vitae nulla ut auctor.",
    },
    {
        title: "Bugs in Germany",
        image: german,
        author: "MJ",
        date: "09/11/2017",
        p1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut congue feugiat pulvinar. Sed vel ex a elit consectetur vestibulum aliquam rhoncus purus. Maecenas ullamcorper non ligula sit amet rhoncus. Integer non ultrices sapien. Cras elit justo, varius a consectetur non, vehicula vitae est. Maecenas in nisi quis arcu molestie mollis. Etiam et luctus ante, id ornare nisl. Morbi eu justo lectus. Vestibulum sodales leo in nisl aliquam, sit amet sagittis nunc efficitur. Vivamus nec lectus dui.",
        p2: "Nam sit amet augue eget risus efficitur vulputate et id ante. Etiam nisi magna, tempor sed magna posuere, ornare gravida nibh. Fusce sit amet viverra sapien. Nam sit amet metus a nibh faucibus gravida ut in metus. Vivamus venenatis neque at metus rutrum, et fringilla ante faucibus. Sed leo arcu, dictum a leo vitae, dignissim gravida mi. Donec scelerisque posuere justo. Sed maximus tempus tellus vitae feugiat.",
        p3: "Cras libero dui, tincidunt ac auctor at, convallis quis ante. Curabitur mi sem, feugiat et velit sed, fermentum malesuada erat. Fusce eu lectus mi. Aenean suscipit ornare risus, ac pellentesque risus mollis in. Maecenas in libero vitae sem pulvinar tincidunt. Curabitur id enim non purus aliquam lobortis. Nullam lacinia purus ac eros gravida malesuada.",
        p4: "Nulla nisl enim, lacinia ac magna quis, dictum mattis diam. Nulla in mi diam. Mauris id mauris in est pharetra efficitur. Nam lacus ex, feugiat vitae nunc bibendum, ullamcorper mattis libero. Donec tincidunt justo ut risus bibendum, ornare mattis orci ultricies. Phasellus vestibulum velit sodales lorem fringilla congue. Duis sagittis sagittis dui nec tincidunt. Nullam tempor pellentesque orci ultrices lobortis. Phasellus ut orci a felis tempor tempus consectetur nec nisi. Etiam sed mattis ante. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec id ipsum sollicitudin, luctus nisl quis, tristique arcu. Nam eget enim imperdiet, scelerisque felis ut, interdum ante.",
        p5: "Donec sollicitudin diam et volutpat ultricies. Sed porta volutpat risus, nec condimentum ligula euismod a. Praesent feugiat felis a porta malesuada. Morbi justo tellus, mollis at ipsum ut, condimentum hendrerit metus. Donec eu lacus tempor, malesuada lacus quis, euismod sem. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer gravida euismod fringilla. Praesent blandit vehicula laoreet. Proin vestibulum sit amet sapien et sodales. Nunc quis tortor et nunc mollis malesuada vel sed eros. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut bibendum varius odio, auctor semper quam. Aliquam sed aliquet nisi. In neque massa, faucibus vel ante id, ultrices varius lacus. Phasellus tincidunt vitae nulla ut auctor.",
    }
]

export default content;